structure:
  inputs: [{name: input, shape: [3, 224, 224]}]
  outputs: [{name: classification, from: [maxvit]}]
  layers:
    - name: maxvit
      from: [input]
      module: lovely_deep_learning.nn.maxvit.MaxVitT
      args: {}

weight:
  path: pretrained_models/maxvit_t-bc5ab103.pth
  url: https://download.pytorch.org/models/maxvit_t-bc5ab103.pth
  map_location: cpu
  strict: false
  src_key_prefix: layers.maxvit.
  src_key_slice_start: 0

