FROM ubuntu:20.04
# 避免交互式安装时的提示
ARG DEBIAN_FRONTEND=noninteractive
# # 代理设置
# ENV http_proxy=http://172.19.134.153:7890
# ENV https_proxy=http://172.19.134.153:7890
# ENV no_proxy=localhost,127.0.0.1,host.docker.internal
# 安装
# RUN apt-get update
# RUN apt-get install cmake -y
# RUN apt-get install libyaml-cpp-dev -y
# # RUN apt-get install build-essential gdb -y
# apt-get install g++ -y
# RUN apt install libgtest-dev -y
# RUN cd /usr/src/gtest && cmake . && make && 
# cp  lib/*.a /usr/lib
# RUN apt-get clean
# RUN rm -rf /var/lib/apt/lists/*
